import { ProfileData } from "./types";

/** Mockup data. Replace with your API response. */
export const sampleProfile: ProfileData = {
  name: "Abdul Bathwin Nasar",
  initials: "AB",
  nuId: "KL11ST03AK",
  verified: true,
  workDone: 0.65,
  rating: 4.8,
  jobs: 24,
  personal: {
    fullName: "Abdul Bathwin Nasar",
    dob: "31-12-1996",
    gender: "Male",
    phone: "+91 91234 56789",
    email: "bathwin.nasar@example.com",
  },
  address: {
    line: "House No. 14, Kuttanellur Road",
    city: "Thrissur",
    pin: "680014",
    district: "Thrissur",
    state: "Kerala",
  },
  education: {
    qualification: "Diploma (ITI)",
    stream: "Electrician",
    studying: true,
    institution: "Govt. Polytechnic College, Thrissur",
    board: "SBTE Kerala",
    institutionCity: "Thrissur",
    course: "B.Voc Renewable Energy",
    currentYear: "2nd year",
    classTimings: "Mon–Fri, 9 am – 1 pm",
    expectedCompletion: "May 2028",
    mode: "Regular",
    yearOfPassing: "2017",
    grade: "78%",
    certificate: "Uploaded 12 Sep 2026",
    certificateVerified: true,
  },
  bank: {
    mode: "bank",
    holder: "Abdul Bathwin Nasar",
    accountNumber: "30214567894821",
    ifsc: "SBIN0070123",
    bankName: "State Bank of India",
    branch: "Thrissur",
    accountType: "Savings",
    upi: "bathwin@oksbi",
    upiVerified: true,
    upiName: "Abdul Bathwin Nasar",
  },
  documents: [
    {
      id: "aadhaar",
      name: "Aadhaar Card",
      number: "XXXX XXXX 5512",
      status: "verified",
      required: true,
      hasBack: true,
      icon: "card",
      numberLabel: "Aadhaar number",
      numberPlaceholder: "1234 5678 9012",
      hint: "Front and back of your Aadhaar card or e-Aadhaar.",
    },
    {
      id: "pan",
      name: "PAN Card",
      number: "ABCPX1234K",
      status: "verified",
      required: true,
      hasBack: false,
      icon: "card",
      numberLabel: "PAN number",
      numberPlaceholder: "ABCDE1234F",
      hint: "Needed for payouts above ₹50,000 a year.",
    },
    {
      id: "pcc",
      name: "Police clearance certificate",
      status: "none",
      required: true,
      hasBack: false,
      icon: "doc",
      numberLabel: "Certificate number",
      numberPlaceholder: "e.g. PCC/TSR/2026/0412",
      hint: "Required for jobs inside clients’ homes. Get it from Kerala Police Thuna.",
    },
    {
      id: "dl",
      name: "Driving License",
      status: "none",
      required: false,
      hasBack: true,
      hasExpiry: true,
      icon: "car",
      numberLabel: "Licence number",
      numberPlaceholder: "KL08 20190012345",
      hint: "Unlocks delivery and driving jobs.",
    },
    {
      id: "voter",
      name: "Voter ID",
      status: "none",
      required: false,
      hasBack: true,
      icon: "card",
      numberLabel: "EPIC number",
      numberPlaceholder: "ABC1234567",
      hint: "Optional extra address proof.",
    },
    {
      id: "cert",
      name: "Education certificate",
      number: "ITI Electrician · 2017",
      status: "review",
      required: false,
      hasBack: false,
      icon: "doc",
      numberLabel: "Certificate / register number",
      numberPlaceholder: "e.g. ITI/TSR/2017/221",
      hint: "Your highest qualification certificate.",
    },
  ],
  skills: null,
  completion: {
    total: 12,
    missing: [
      {
        id: "photo",
        label: "Profile photo",
        sub: "Clients trust workers with a clear face photo",
      },
      {
        id: "emergency",
        label: "Emergency contact",
        sub: "Someone we can call if you’re unreachable on a job",
      },
      {
        id: "skills",
        label: "Skills & experience",
        sub: "Helps match you to the right jobs",
      },
    ],
  },
};
